# Generated by Django 4.1.7 on 2023-02-16 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='professores', to=settings.AUTH_USER_MODEL),
        ),
    ]
