# Generated by Django 4.1.7 on 2023-02-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_student_customuser_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveBigIntegerField(choices=[(1, 'student'), (2, 'teacher')], default=1),
            preserve_default=False,
        ),
    ]
