# Generated by Django 4.1.7 on 2023-02-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codico_criacao_teacher',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
